{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple.fullname" . }}
  labels:
    {{- include "simple.labels" . | nindent 4 }}
data:
  password: {{ .Values.secrets.password | b64enc | quote }}
{{- end }}
